[font]
size = 13
[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
[shell]
program = "tmux"
[env]
term = "xterm-256color"
[[keyboard.bindings]]
key = "("
mods = "Control|Shift"
chars = "\uE000"
[[keyboard.bindings]]
key = ")"
mods = "Control|Shift"
chars = "\uE001"