[window]
decorations = 'None'
[font]
size = 13
[font.normal]
family = "CaskaydiaMono Nerd Font Propo"
[terminal.shell]
program = "tmux"
[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\uE002"
